apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hiererchical-opa-act1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: hierarchical-opa-act1
    name: act1
  project: hierarchycal-opa
  source:
    repoURL: https://github.com/csomaati/argocd-example-apps.git
    path: example-app/config/opa-act1

