apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: opa-act1
  name: opa-act1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa-act1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: opa-act1
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
