apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: opa-prod
  name: opa-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa-prod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: opa-prod
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
